# Generated by Django 4.0.6 on 2024-04-16 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lusofona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='ano',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='ects',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='disciplina',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='lusofona.disciplina'),
        ),
    ]
