# Generated by Django 4.0.6 on 2024-04-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lusofona', '0003_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='disciplinas',
            field=models.ManyToManyField(related_name='cursos', to='lusofona.disciplina'),
        ),
        migrations.AddField(
            model_name='docente',
            name='disciplinas',
            field=models.ManyToManyField(related_name='docentes', to='lusofona.disciplina'),
        ),
        migrations.AlterField(
            model_name='areacientifica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='ects',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='semestre',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='docente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='linguagemprogramacao',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
