# Generated by Django 4.0.6 on 2024-04-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('praias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='praia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='praias.praia'),
        ),
        migrations.AlterField(
            model_name='regiao',
            name='concelho',
            field=models.CharField(max_length=200),
        ),
    ]
