# Generated by Django 4.0.6 on 2024-04-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praias', '0002_servico_praia_alter_regiao_concelho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='praia',
        ),
        migrations.AddField(
            model_name='servico',
            name='praias',
            field=models.ManyToManyField(related_name='servicos', to='praias.praia'),
        ),
    ]
