# Generated by Django 4.0.6 on 2024-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praias', '0003_remove_servico_praia_servico_praias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='praias',
            field=models.ManyToManyField(null=True, related_name='servicos', to='praias.praia'),
        ),
    ]
