# Generated by Django 4.0.6 on 2024-04-16 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='capa_album',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='album',
            name='gravadora',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banda',
            name='ano_formacao',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='banda',
            name='genero',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banda',
            name='pais_origem',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='duracao',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='musica',
            name='numero_faixa',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='banda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='bandas.banda'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='bandas.album'),
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('papel_na_banda', models.CharField(max_length=100, null=True)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='bandas.banda')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='bandas.album')),
            ],
        ),
    ]
